spring:
  datasource:
    secondary:
      jdbc-url: "jdbc:sqlserver://192.168.28.24:1433;databaseName=UFDATA_999_2025;encrypt=true;trustServerCertificate=true"
      username: sa
      password: Aa123456
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      hikari:
        pool-name: SecondarySQLServerPool
        maximum-pool-size: 5
        connection-timeout: 30000

mybatis:
  secondary:
    mapper-locations: classpath:mapper/U8/*.xml
    type-aliases-package: com.zhonghe.adapter.model.U8

logging:
  level:
    com.zhonghe.adapter.mapper.U8: DEBUG