logging:
  level:
    com.zhonghe.adapter.mapper.U8: DEBUG
    com.zhonghe.adapter.mapper.BIP: DEBUG
    com.zhonghe.adapter.feign: DEBUG
    feign.Logger: DEBUG
    feign.okhttp.OkHttpClient: DEBUG
    org.apache.http.wire: DEBUG

# 钉钉配置
dingtalk:
  appKey: "ding3oj3qnkgx7ykeqbt"
  appSecret: "XCIAXNf3Sja7E4IWpR0lyeVs-NnIekQ--8GPo3hdiK53HdlwzDqflUKV5rDJF_jn"
  serverUrl: "https://oapi.dingtalk.com"
  timeout: 5000

bip:
  config:
    ip: "192.168.10.51"
    port: "9090"
    biz-center: "LT"
    client-id: "dingding"
    client-secret: "46742db37b3948e2bfef"
    pub-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqQLfSbqXDtvg2IucmyI8c0RB678h6dgfKncuDIU+fQmYUVdbUmV7ZKEjFjolo7xqN9SMjrSVUIX4c3AqovzX7NbCVHfQkxmk3SeiIsF8lvjEAMqra5xH9VaZnbSmeyh143bXzO9SJgdegLOQOV2SeENy93BFAyr16Q1E1AYsMq0xmoc/D+fbxDN94aDNKbwzEcSttOVXuOHziF3uO42/8oHYcN3dbudJAu6FkSqR4b5m1ZDVcJb1Q7KcVs44jQ8cpZWBa97RN7S9xROVMnIF43G33Gi7WdwgsbExozaeco3OK3Bew0Z0BLkz1q1G+nF6GqpHgyd1ftrLaL6y9UVBTQIDAQAB+hDwpvAZBUPVem52kfJibm4UPobviXLrWuuahRcrzvVWX6JKlRmDXuFhUw7VomlOYp5kUqOelV6LO9ShKoxx+awtNexvSsEPOX0qluF5TuuSI7jphKSrw3CmCpQcWrOmOBxjsbuKLt3Xu76WDtMmsjiW8HEbL4NbI3/T6hs7b95qbvbm4UJqKQTl1ukQUlV97fboRwPCT+OHmFjJOhQnWg3p65iuQcQwC2yTHM1S2lY8G7xiTvofh3e/Mtb7wXt89mOV4VdS7QdXKEisjM1i7SYiwBLzPKJnV97hCQcV6t/l0Ta0/KHLIwzAfkKgJ2vtjFm1cnhwIDAQAB"
    user-name: "admin04"
    pwd: ""
    tenant-id: null
    secret-level: "L0"
    grant-type: "client"