spring:
  datasource:
    secondary:
      jdbc-url: "jdbc:sqlserver://192.168.4.8:1433;databaseName=UFDATA_999_2025;encrypt=true;trustServerCertificate=true;serverTimezone=Asia/Shanghai"
      username: sa
      password: sy1901!!
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      hikari:
        pool-name: SecondarySQLServerPool
        maximum-pool-size: 10
        maxLifetime: 1800000
        idleTimeout: 600000
        validation-timeout: 5000

mybatis:
  secondary:
    mapper-locations: classpath:mapper/U8/*.xml
    type-aliases-package: com.zhonghe.adapter.model.U8

logging:
  level:
    com.zhonghe.adapter.mapper.U8: DEBUG
    com.zhonghe.adapter.feign: DEBUG

    # 启用 Feign 底层日志
    feign.Logger: DEBUG

    # 可选：启用 HTTP 客户端日志（如果是 OkHttp 或 Apache HttpClient）
    feign.okhttp.OkHttpClient: DEBUG
    org.apache.http.wire: DEBUG