spring:
  datasource:
    # 主数据源（MySQL）
    backoffice:
      jdbc-url: "jdbc:mysql://localhost:3306/aite?useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true"
      username: root
      password: Root@1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        pool-name: PrimaryMySQLPool
        maximum-pool-size: 20
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000

    secondary:
      jdbc-url: "jdbc:sqlserver://192.168.28.24:1433;databaseName=UFDATA_999_2025;encrypt=true;trustServerCertificate=true"
      username: sa
      password: Aa123456
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      hikari:
        pool-name: SecondarySQLServerPool
        maximum-pool-size: 5

  liquibase:
    url: jdbc:mysql://localhost:3306/aite?useSSL=false&serverTimezone=Asia/Shanghai
    user: root
    password: Root@1234
    enabled: false
    change-log: classpath:db/changelog/backoffice-changelog-master.yaml
    default-schema: aite
#  quartz:
#    job-store-type: jdbc
#    jdbc:
#      initialize-schema: always
#    properties:
#      org:
#        quartz:
#          jobStore:
#            tablePrefix: QRTZ_
#            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#            useProperties: true
#          scheduler:
#            instanceName: BackofficeScheduler
#            instanceId: AUTO
#          threadPool:
#            threadCount: 5
mybatis:
  executor-type: batch
  mapper-locations:
    - classpath*:mapper/*.xml
  type-aliases-package: com.zhonghe.backoffice.model
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    org.mybatis: DEBUG
    com.zhonghe.backoffice.mapper: DEBUG
    com.zhonghe.adapter.feign: DEBUG
    feign.Logger: DEBUG

feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

api:
  base-url: hcapi.hnkingdee.cn:60002
  sign-header-value: NsRm1fqs+mEW0MROZM4w5w==

app:
  batch:
    master-size: 500
    detail-size: 2000

