spring:
  datasource:
    backoffice:
      jdbc-url: "jdbc:mysql://localhost:3306/aite?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
      username: root
      password: Root@1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        pool-name: PrimaryMySQLPool
        maximum-pool-size: 10
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/backoffice-changelog-master.yaml
    default-schema: aite

mybatis:
  mapper-locations:
    - classpath*:mapper/*.xml
  type-aliases-package: com.zhonghe.backoffice.model
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    org.mybatis: DEBUG
    com.zhonghe.backoffice.mapper: DEBUG

api:
  base-url: http://hndbkd.top:54351
  sign-header-value: NsRm1fqs+mEW0MROZM4w5w==